[package]
name = "zest"
version = "0.6.4-unstable"
edition = "2021"
repository = "https://github.com/toiletbril/zest"
authors = ["toiletbril"]

[profile.release]
opt-level = 3
strip = true
lto = true

[dependencies]
toiletcli = "0.6.1"
